CREATE TABLE ALUMNOS (
    ID_ALUMNOS NUMBER(5) PRIMARY KEY,
    APELLIDO VARCHAR2(30),
    NOMBRES VARCHAR2(30),
    FECHA_NACIMIENTO DATE,
    TELEFONO NUMBER(9)
);

INSERT INTO ALUMNOS VALUES (1, 'RAMOS', 'JUAN', TO_DATE('2007-07-25', 'YYYY-MM-DD'), 987654321);
INSERT INTO ALUMNOS VALUES (2, 'ENRIQUEZ', 'DIEGO', TO_DATE('2007-07-25', 'YYYY-MM-DD'), 912345678);
INSERT INTO ALUMNOS VALUES (3, 'ROSALES', 'LIZ', TO_DATE('2008-02-13', 'YYYY-MM-DD'), 934567890);

CREATE TABLE CURSOS (
    ID_CURSOS NUMBER(5) PRIMARY KEY,
    NOMBRE_CURSOS VARCHAR2(30),
    CREDITO NUMBER(10,2)
);
INSERT INTO CURSOS VALUES (100, 'PROGRAMACION', 4.00);
INSERT INTO CURSOS VALUES (101, 'CALCULO', 3.50);
INSERT INTO CURSOS VALUES (102, 'RELIGION', 2.00);

CREATE TABLE INSCRIPCIONES (
    ID_INSCRIPCIONES NUMBER(5) PRIMARY KEY,
    ID_ALUMNOS NUMBER(5),
    ID_CURSOS NUMBER(5),
    FECHA_INSCRIPCION DATE,
    CONSTRAINT FK_INSCRIPCION_ALUMNOS FOREIGN KEY (ID_ALUMNOS) REFERENCES ALUMNOS(ID_ALUMNOS),
    CONSTRAINT FK_INSCRIPCION_CURSOS FOREIGN KEY (ID_CURSOS) REFERENCES CURSOS(ID_CURSOS)
);

INSERT INTO INSCRIPCIONES VALUES(1000 , 1 , 100 , SYSDATE);
INSERT INTO INSCRIPCIONES VALUES(1001, 2, 101, SYSDATE);
INSERT INTO INSCRIPCIONES VALUES(1002, 3, 102, SYSDATE);


SELECT * FROM ALUMNOS;
SELECT * FROM CURSOS;
SELECT * FROM INSCRIPCIONES;