CREATE TABLE ALUMNO (
    ID_ALUMNO NUMBER(5) PRIMARY KEY,
    DNI NUMBER(8) UNIQUE NOT NULL,
    APELLIDO VARCHAR2(30) NOT NULL,
    NOMBRES VARCHAR2(30) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    TELEFONO NUMBER(9) NOT NULL,
    CONSTRAINT CHK_DNI CHECK (DNI BETWEEN 10000000 AND 99999999),
    CONSTRAINT CHK_TELEFONO CHECK (TELEFONO BETWEEN 100000000 AND 999999999)
);


INSERT INTO ALUMNO (ID_ALUMNO, DNI, APELLIDO, NOMBRES, FECHA_NACIMIENTO, TELEFONO)
VALUES (1, 74859632, 'RAMOS', 'JUAN', TO_DATE('2007-07-25', 'YYYY-MM-DD'), 987654321);

INSERT INTO ALUMNO (ID_ALUMNO, DNI, APELLIDO, NOMBRES, FECHA_NACIMIENTO, TELEFONO)
VALUES (2, 75968421, 'ENRIQUEZ', 'DIEGO', TO_DATE('2007-07-25', 'YYYY-MM-DD'), 912345678);

INSERT INTO ALUMNO (ID_ALUMNO, DNI, APELLIDO, NOMBRES, FECHA_NACIMIENTO, TELEFONO)
VALUES (3, 76843295, 'ROSALES', 'LIZ', TO_DATE('2008-02-13', 'YYYY-MM-DD'), 934567890);


CREATE TABLE CURSO (
    ID_CURSO NUMBER(5) PRIMARY KEY,
    NOMBRE_CURSO VARCHAR2(30) NOT NULL UNIQUE,
    CREDITO NUMBER(10,2) NOT NULL,
    CONSTRAINT CHK_CREDITO CHECK (CREDITO > 0)
);


INSERT INTO CURSO VALUES (100, 'PROGRAMACION', 4.00);
INSERT INTO CURSO VALUES (101, 'CALCULO', 3.50);
INSERT INTO CURSO VALUES (102, 'RELIGION', 2.00);


CREATE TABLE INSCRIPCIONES (
    ID_INSCRIPCIONES NUMBER(5) PRIMARY KEY,
    ID_ALUMNO NUMBER(5) NOT NULL,
    ID_CURSO NUMBER(5) NOT NULL,
    FECHA_INSCRIPCION DATE,
    
    CONSTRAINT FK_INSCRIPCION_ALUMNO FOREIGN KEY (ID_ALUMNO) REFERENCES ALUMNO(ID_ALUMNO),
    CONSTRAINT FK_INSCRIPCION_CURSO FOREIGN KEY (ID_CURSO) REFERENCES CURSO(ID_CURSO)
);

INSERT INTO INSCRIPCIONES VALUES(1000 , 1 , 100 , SYSDATE);
INSERT INTO INSCRIPCIONES VALUES(1001, 2, 101, SYSDATE);
INSERT INTO INSCRIPCIONES VALUES(1002, 3, 102, SYSDATE);